baseurl = "https://jaydeepfoujdar.github.io/"
languageCode = "en-US"
title = "Jaydeep Foujdar"
# Enable comments by entering your Disqus shortname
disqusShortname = "dhavalgujar.disqus.com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile1.png"
  author = "Dhaval Gujar"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "dhavalgujar"
  Email         = "dhvlgjr@gmail.com"
  Twitter       = "dhavalgujar"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
